### ISSUE TITLE
ranges with char numbers doesn't seem to work 

### ISSUE THREAD

**Issue by husio-org** [zaach/lex-parser#5]
```
letter     [a-zA-Z] 
```

works fine,

however 

```
asciichar [\32-\126] 
```

doesn't seems to work.

**Comment by husio-org** [comment]
just noticed that using the hex notation seems to work:

```
asciichar [\x20-\x7f]
```

which workarounds this issue fine

**Comment by zaach** [comment]
Yeah – it uses JavaScript regular expressions under the hood, which don't recognize the `\00` format.
